# Generated by Django 5.0.6 on 2024-06-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_categoryt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_categoryt',
            new_name='tbl_category',
        ),
    ]
