# Generated by Django 5.0.6 on 2024-06-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_tbl_categoryt_tbl_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_category',
            old_name='catogery_name',
            new_name='categery_name',
        ),
    ]
