# Generated by Django 5.0.6 on 2024-06-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_rename_catogery_name_tbl_category_categery_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_category',
            old_name='categery_name',
            new_name='category_name',
        ),
    ]
