# Generated by Django 5.0.6 on 2024-06-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_rename_categery_name_tbl_category_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adminregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminRegistration_name', models.CharField(max_length=50)),
                ('AdminRegistration_email', models.CharField(max_length=50)),
                ('AdminRegistration_password', models.CharField(max_length=50)),
            ],
        ),
    ]
