# Generated by Django 5.0.6 on 2024-06-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_adminregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_adminregistration',
            new_name='tbl_Registration',
        ),
        migrations.RenameField(
            model_name='tbl_registration',
            old_name='AdminRegistration_email',
            new_name='Registration_email',
        ),
        migrations.RenameField(
            model_name='tbl_registration',
            old_name='AdminRegistration_name',
            new_name='Registration_name',
        ),
        migrations.RenameField(
            model_name='tbl_registration',
            old_name='AdminRegistration_password',
            new_name='Registration_password',
        ),
    ]
