# Generated by Django 5.0.6 on 2024-09-19 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0012_tbl_company_tbl_newshop'),
        ('User', '0013_tbl_scrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shopbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopbooking_date', models.DateField(auto_now_add=True)),
                ('shopbooking_status', models.IntegerField(default=0)),
                ('scarp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_scrap')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newshop')),
            ],
        ),
    ]
