# Generated by Django 5.1.2 on 2024-10-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_companybooking',
        ),
    ]
