# Generated by Django 5.1.2 on 2024-10-16 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0002_delete_tbl_companybooking'),
        ('Guest', '0012_tbl_company_tbl_newshop'),
        ('User', '0013_tbl_scrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_companybooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companybooking_date', models.DateField(auto_now_add=True)),
                ('companybooking_status', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('scarp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_scrap')),
            ],
        ),
    ]
