# Generated by Django 5.0.6 on 2024-07-05 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=50)),
                ('User_Address', models.CharField(max_length=50)),
                ('User_Contact', models.CharField(max_length=50)),
                ('User_Email', models.CharField(max_length=50)),
                ('User_Gender', models.CharField(max_length=50)),
                ('User_Dob', models.CharField(max_length=50)),
                ('User_Password', models.CharField(max_length=50)),
                ('User_Photo', models.FileField(upload_to='Aassets/User/')),
                ('Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
