# Generated by Django 5.0.6 on 2024-08-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_NewShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewShop_Name', models.CharField(max_length=50)),
                ('NewShop_Email', models.CharField(max_length=50)),
                ('NewShop_Contact', models.CharField(max_length=50)),
                ('NewShop_Address', models.CharField(max_length=50)),
                ('NewShop_Photo', models.FileField(upload_to='Assets/NewShop/Photo/')),
                ('NewShop_Proof', models.FileField(upload_to='Assets/NewShop/Proof/')),
            ],
        ),
    ]
