# Generated by Django 5.0.6 on 2024-08-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_tbl_newshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_NewShop',
        ),
    ]
