# Generated by Django 5.0.6 on 2024-08-26 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_newshop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newShop',
        ),
    ]
