# Generated by Django 5.0.6 on 2024-08-26 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_place'),
        ('Guest', '0008_delete_tbl_newshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_Name', models.CharField(max_length=50)),
                ('Shop_Email', models.CharField(max_length=50)),
                ('Shop_Contact', models.CharField(max_length=50)),
                ('Shop_Address', models.CharField(max_length=50)),
                ('Shop_Photo', models.FileField(upload_to='Assets/NewShop/Photo/')),
                ('Shop_Proof', models.FileField(upload_to='Assets/NewShop/Proof/')),
                ('Shop_status', models.IntegerField(default='0')),
                ('Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
