# Generated by Django 5.0.6 on 2024-08-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_tbl_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_newshop',
            name='Place',
        ),
        migrations.DeleteModel(
            name='tbl_company',
        ),
        migrations.DeleteModel(
            name='tbl_newShop',
        ),
    ]
