# Generated by Django 5.0.6 on 2024-08-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scrap_Category', models.CharField(max_length=50)),
                ('Scrap_Quantity', models.CharField(max_length=50)),
                ('Scrap_Description', models.CharField(max_length=50)),
                ('Scrap_Price', models.CharField(max_length=50)),
                ('Scrap_Photo', models.FileField(upload_to='Assets/Scrap/Photo/')),
            ],
        ),
    ]
