# Generated by Django 5.0.6 on 2024-08-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaints_Title', models.CharField(max_length=50)),
                ('Complaints_Content', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='tbl_complaint',
            new_name='tbl_Scrap',
        ),
    ]
