# Generated by Django 5.0.6 on 2024-08-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_complaints_rename_tbl_complaint_tbl_scrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_Content', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='tbl_complaints',
            old_name='Complaints_Content',
            new_name='Complaint_Content',
        ),
        migrations.RenameField(
            model_name='tbl_complaints',
            old_name='Complaints_Title',
            new_name='Complaint_Title',
        ),
    ]
