# Generated by Django 5.0.6 on 2024-08-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_feedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Scrap',
        ),
    ]
