# Generated by Django 5.0.6 on 2024-08-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_subcategory'),
        ('Guest', '0012_tbl_company_tbl_newshop'),
        ('User', '0004_delete_tbl_scrap'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Scrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scrap_Category', models.CharField(max_length=50)),
                ('Scrap_Quantity', models.CharField(max_length=50)),
                ('Scrap_Description', models.CharField(max_length=50)),
                ('Scrap_Price', models.CharField(max_length=50)),
                ('Scrap_Photo', models.FileField(upload_to='Assets/Scrap/Photo/')),
                ('Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newshop')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
            ],
        ),
    ]
