# Generated by Django 5.0.6 on 2024-08-28 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_company_tbl_newshop'),
        ('User', '0005_tbl_scrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scrap',
            name='Shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_newshop'),
        ),
    ]
