# Generated by Django 5.0.6 on 2024-09-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_tbl_scrap_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_Complaints',
            new_name='tbl_Complaint',
        ),
    ]
