# Generated by Django 5.0.6 on 2024-09-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_tbl_complaints_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Complaint',
        ),
    ]
