# Generated by Django 5.0.6 on 2024-09-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_FeedBack',
        ),
    ]
