# Generated by Django 5.0.6 on 2024-09-17 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_company_tbl_newshop'),
        ('User', '0010_delete_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_Content', models.CharField(max_length=50)),
                ('Feedback_Date', models.DateField(auto_now_add=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_company')),
                ('Shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_newshop')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_user')),
            ],
        ),
    ]
