# Generated by Django 5.0.6 on 2024-09-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_Scrap',
        ),
    ]
