# Generated by Django 5.1.2 on 2024-10-16 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_company_tbl_newshop'),
        ('User', '0013_tbl_scrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_scrap',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_user'),
        ),
    ]
